<a href="https://colab.research.google.com/github/youngjinjae/pythontest/blob/main/0718_python_%ED%95%A8%EC%88%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# python의 함수는 ??
# 일단 함수명은 가독성을 높이기 위해 소문자로 다수 사용
# JAVA 같은 경우 camel case,
# python은 분리된 단어는 밑줄로 표현 snake case
# myFunc - java, my_func - python

# 사용자 정의 함수를 만들자.
# 사용자 함수 정의 def
# def my_sum(a,b,c):
#     return a + b + c

# result = my_sum(1,2,3)
# print(result)

#함수의 body 없는 경우 사용 방법
# def my_sum(a,b,c):
#     pass
# pass 사용시 무시한다 .실행을 하지않는다.
# python은 여러개의 값을 리턴

# def my_sum(a,b,c):
#     result1 = a + b  + c
#     result2 = a * b * c
#     return result1, result2

# result = my_sum (1,2,3)
# print(result) #(6,6)

# return 여러개 값을 리턴을 잘못된 표현이고
# 실제로는 tuple를 리턴

# tmp = 100 # 값을 넣어줌

# def my_func(x):  # 함숮정의
#     tmp += x
#     return tmp
# # 여기서 지역 변수가 아닌 전역 변수를 사용 할수 있다.
# # global 의 변수 사용시 tmp 밖에 내용을 가지고온다.
# result = my_func(100) # print 하기위한 값 넣김
# print(result)
# # error 밖에 있는 tmp100 은 def 정의한 tmp의 값을 대입못함
# tmp = 100 # 값을 넣어줌

# def my_func(x):  # 함숮정의
#     global tmp
#     tmp += x
#     return tmp
# # 여기서 지역 변수가 아닌 전역 변수를 사용 할수 있다.
# # global 의 변수 사용시 tmp 밖에 내용을 가지고온다.
# result = my_func(100) # print 하기위한 값 넣김
# print(result)
# # 전역 변수를 사용하면 코드가 tightly coupled 됨







200


In [ ]:
# 내장 함수
# 너무 많다. 나오는대로 보자.

# a = int(100)
# pritn(a)
# a = int ('100')
# print(a)

result = len('이것은 소리없는 아웅성')
print(result) # 12 해당 문자열의 길이 갯수 샐때도 len도 가능하다
# type, list, dic, tuple, set,


12


In [ ]:
# 함수 사용 시 찾아보기

# 이제 python 에 대해 알아보자.
# python 객체지향은
# class 나옴 상속 기타 객체 지향
# 파이썬 익숙하고 나서 공부

# python 언어에 대한 기본적인 내용을 이해
# 데이터 처리쪽으로

# 1, 순위 공부 numpy 라는 module임

# numpy는 numerical Python 약자이다.

# numpy는 module 라이브러리이다.
# 수학적 처리를 쉽게 할 수 있도록 도와주는 역활이다.
# numpy 는 대규모의 다차원 배열과 행렬처리를 편하게 처리
# 다차원 배열 ~
# 머신러닝과 딥러닝은 수학계산 행렬 계산 수치계산
# 그래서 ML, DL 기본 자료구조를 NUMPY의 자료구조기본
# numpy 딱 1개의 ndarray 라는
# ndarray 다차원 배열로 진행 - (n-dimensional array)만듬
# 자료구조 만들어줌 기본 자료구조 제공



In [ ]:
# numpy 는 외부 module이라서 사용하면 설치 필요
# 우리 가상환경에 설치
# conda install numpy 내 코드내로 사용한다.

import  numpy as np
print (numpy.__version__)

1.24.3


In [ ]:
# ndarray 생성 및 확인

# 쉬운 방법 ndarray 를 list 로 이용
a = [1,2,3,4]
print(a) #[1,2,3,4] 1 차원
print (type(a)) # <class'list'>

b = np.array([1,2,3,4]) # numpy 기능 중에 ndarray를 만들어봐라
print(b) #1 차원 vector [1 2 3 4] , 이 없다~
print(type(b)) # <class 'numpy.ndarray'>


[1, 2, 3, 4]
<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
# 2차원 형태의 ndarray

my_list = [[1,2,3],[4,5,6]] # 중첩 list
arr = np.array(my_list)

print(arr) # 2ckdnjs ndarray를 만듬 2행 3열
            # [[1,2,3]
            # [4,5,6]]
print(arr[1,1]) #5 python은 이렇게 표현할 시에는 오류 #ndarray만 가능
print(arr[1]) #[4,5,6] 1c차원 ndarray
print(arr[1][2]) #6



[[1 2 3]
 [4 5 6]]
5
[4 5 6]
6


In [ ]:
my_list = [[1,2,3],[4,5,6]] # 중첩 list
# 일반적으로 ndarray 사용 할 때는 모두 실수 사용해야함
arr = np.array(my_list, dtype=np.float64) #np안에 float64 가진 값을 데이터 타입 지정
print(arr) #뒤에 보면 이제 실수형으로 변환
#             [[1. 2. 3.]
#             [4. 5. 6.]]



[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
my_list = [[1,2,3],[4,5,6.0]] # 중첩 list
arr = np.array(my_list)
print(arr)

# 일반적으로 ndarray 사용 할 때는 모두 실수 사용
# array의 특징 일단 사이즈가 결정되면 변경할 수 없다.
#              모든 칸에 데이터 타입이 들어간다.

# 결과값이 전부 실수로 float 변경 6.0 으로 인해 나머지가 0.0 으로 표현

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
my_list = [1,2,3,4]
arr = np.array(my_list) # 1차원 ndarray 이 만듬
print(arr)
# ndarray 두가지 속성
print(arr.ndim) #ndim 속성 몇 차원이여? 1 차원~ 차원값 알려줌
print(arr.shape) # 결과값은 tuple로 표현
                #(3,) 1차원  3개
                #(4,5) 2차원 4*5 20개 정도
                #(1,5,3) 3차원
                # 그리고 숫자는 해당 차원의 요소수를 표현
                #(4,) 몇차원인지 알려줌

my_list = [[1,2,3],[4,5,6]]
arr = np.array(my_list) # 2차원 ndarray 이 만듬
print(arr)
print(arr.ndim)  # 2차원
print(arr.shape) # 2행 3열 입니다. 6개

my_list = [[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]
arr = np.array(my_list) # 3차원 ndarray 이 만듬
print(arr)
print(arr.ndim)  # 3차원
print(arr.shape) # 2행 3열 3개

# ndim 는 shape 으로 다 나옴 차우너 설명 몇개 까지 나옴


[1 2 3 4]
1
(4,)
[[1 2 3]
 [4 5 6]]
2
(2, 3)
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3
(2, 2, 3)


In [ ]:
my_list = [[1,2,3],[4,5,6]]
arr = np.array(my_list) # 2차원 ndarray 이 만듬
print(arr)
print(arr.size) #요소의 갯수 6개
print(len(arr)) # 일반적으로 사용x 전체사이즈 안함 상위 차원요소 개수

[[1 2 3]
 [4 5 6]]
6


In [ ]:
my_list = [[1,2,3],[4,5,6]]
arr = np.array(my_list) # 2차원 ndarray
#내가 가지고 있는 ndarry의 데이터 타입을 변환
# 정수 - 실수로 변경 또는 실수에서 정수 변경
arr = arr.astype(np.float64) 실수로

print(arr)

In [ ]:
# 그러면 np.array() 이렇게 만드는 방법 말고 다른 방법은 없나요.
# 지금까지 list 를 가지고 해당 list 데이터를 이용 ndarray
# 다르게 만드는 방법

# shape을 tuple로 표현
arr = np.zeros
print(arr)

arr = np.zeros((3,4)) # 인자로 들어온 shape 형태로 0으로 표현 ndarray
print(arr)

arr = np.ones((3,4)) # shape 형태로 1로 초기화 표현 ndarray
print(arr)

arr = np.empty((4,5)) # shape 형태로 초기화가 안된 ndarray 생성
print(arr)                 # 쓰레기 값을 있음 그러니 주의해서 사용

arr = np.full((4,5),7) # shape 형태로 내가 결정한 초기값으로 ndarray 표현
print(arr)             # 값 7


<built-in function zeros>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.69120688e-306
  1.33511018e-306]
 [1.33511969e-306 6.23037996e-307 1.69121639e-306 1.78019082e-306
  1.33511290e-306]
 [1.11261027e-306 1.11261502e-306 1.42410839e-306 7.56597770e-307
  6.23059726e-307]
 [1.42419530e-306 1.78019354e-306 1.69119330e-306 8.34444289e-308
  8.34402698e-308]]
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [ ]:
# numpy array 생성하는 또 다른 방법
# arr = np.zeros((3,4))
arr = np.arange(10)
print(arr)
# arange() 함수가 있음 python의 range() 유사하다.
# python의 ragne() 데이터를 가지고 있지않아요. 범위를 지칭하는 자료구조
# numpy의 arange() 이용하면 실제 데이터를 가지는 ndarray를 생성

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# numpy array 생성하는 또 다른 방법
# random 기반으로 생성하는 방법

# 방식이 총5개 정도
# 가장 대표적인 2개의 함수 사용 나머지는 예제로 나올때 정리 암기

# np.random.normal() # 이거 이용하면 랜덤값을 채워짐 ndarray를 만들어낸다.

# 일반 정규분포는 평균과 표준 편차를 이해해야함
# mean = 50 # ex) 50 잡음 평균
# std = 2  # ex) 표준편차 2 로 잡음

# arr = np.random.normal(mean,std,(3,4)) # 값을 대입하고, 난수를 발생 시켜야함
# print(arr)                             #shape (3,4)
                                        #normal 정규분포 이다 .


##################################################################
# 주어진 범위 내에서 정수형 난수를 균등분포로 도출해주는 함수
# arr = np.random.randint(1,45,(5,6))
# print(arr)

arr = np.random.randint(0,100,(3,4))
print(arr)
# 균등분포를 출력하다.
# 정수형 난수를 원하고 랜덤값으로 균등하게 나온다.
# 계속해서 출력 시에는 변경되다.

# 랜덤값은 난수라고 표현하는것은
# 컴퓨터는 난수를 도출 할대 특정 알고리즘 사용

#np.ramdom.seed(1) 결과값이 고정한다.
# arr = np.random.randint(0,100,(3,4))
# print(arr)
# seed 값은 고정해준다. 항상 같은 값을 만들어준다.


[[40 79 72 27]
 [71 92 62 58]
 [82 17 74 93]]


In [ ]:
# shape
# 이 shape d을 우리가 원하는대로 변경
my_list = [[1,2,3],[4,5,6]]
arr = np.array(my_list) # 2차원
print(arr)
print(arr.shape) #(2,3) 6개

# newArr = arr.reshape(3,5) # 다시 오류난다. 6개졌다
newArr=arr.reshape(3,2)
print(newArr)

print(newArr[0,0]) # 1 이 나온다.
newArr[0,0] = 100 # 0,0 자리에 1에 자리를 변경한다.
print(newArr)
print(arr) # 실제 데이터는 원본에서 데리고 온다.
            #reshape 하면 새로운 ndarray가 만들어지는게 아니다.
    # view 가 원본이 만들어진다.
    # shape만 바꿔서 표현 데이터는 원본으로 직접 가져와서 모양 바껴서 표현

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
1
[[100   2]
 [  3   4]
 [  5   6]]
[[100   2   3]
 [  4   5   6]]


In [ ]:
my_list = [[1,2,3],[4,5,6]]
arr = np.array(my_list) # 2차원

print(arr) # 2x 3
# 이번에 약간 다르게 표현
# -1 의미를 이해 위주

newArr = arr.reshape(1,6) #1행 6열로 6개 갯수만 잡으면 된다.
print(newArr)

newArr = arr.reshape(-1,6) # (-1,2) 2개의 열로 하고 나머지는 알아서
print(newArr)

newArr = arr.reshape(-1,2,3) # 남는 면 나오나
print(newArr)

newArr = arr.reshape(-1,1,3) # 이렇게 (-1,-1,3) x -1 안된다 가운데는
print(newArr)


[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]
[[1 2 3 4 5 6]]
[[[1 2 3]
  [4 5 6]]]
[[[1 2 3]]

 [[4 5 6]]]


In [ ]:
# ndarray를 하나 만들기
# copy( ) 이용하면 진짜 ndarray 메모리상

arr = np.arange(12).reshape(3,4).copy()
print(arr)

# 많이 사용하는 함수 중에 reshape() 있고 ravel()
# reshape()은 내가 원하는 형태에 view 만들어 주는 함수
# ravel() 무조건 1차원 view 생성
print(arr.ravel())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# 이방싟은 많이 사용 안함
# 기본적인 방법

arr = np.arange(12).reshape(3,4).copy()
print(arr)
newArr = np.resize(arr,(3,5)) # 원소의 수가 맞지않아도 변경 가능
                            # 당연히 view가 아닌 다른 ndarray를 생성
print(newArr) # 원래 데이터를 다시 처음부터 깔라~ 012 다시 마지막
newArr = np.resize(arr,(2,2)) # resize는 데이터값이 짤리고 다시 생성시
print(newArr)                # 랜덤값이 들어간다.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11  0  1  2]]
[[0 1]
 [2 3]]


In [ ]:
# 이제 ndarray 에 대해서 알기
# indexing, slicing를 이해
arr = np.arange(10,20,1) #10~19 까지 1차원
print(arr)
print(arr[2]) # 12
print(arr[:]) # 12
print(arr[5:-1]) # 15~18 까지 표현 slicing의 결과는 1차원 원본가 같은 구조


arr = np.arange(10,22,1).reshape(3,4) #3,4 까지 1차원
print(arr)

print(arr[1,3]) # indexing = 17

print(arr[2,:]) # 열은 처음부터 끝까지 앞에는 indexing, slicing 이다

print(arr[1:2,0:2]) # [14,15]




[10 11 12 13 14 15 16 17 18 19]
12
[10 11 12 13 14 15 16 17 18 19]
[15 16 17 18]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
17
[18 19 20 21]
[[14 15]]


In [ ]:
# indexing은 위에서 햇던 것처럼 기본적인 infexi$ng

# 1.Boolean indexing
# 2.fancyindoein

# 3.1boolean indexing 부터 알아보기
# 배열의 각 요소의 indexing 선택여부
# true/fasle 구성된 boolean mask 를 이용
# 지정하는 방식의미
# boolean mask 에서 true 지정된 요소 대해서
#indexing 데이터 정제나 모델링핸들링
np.random.seed(1)
arr = np.random.randint(0,10,(10,)) #난수 추출
print(arr)

# 구하고 싶은거 이 중에 짝수만 구하시오.
# 당연히 boolean mask 만들기
# ndarray에 대해서 연산을 수행하면 broadcasting과 각 위치에 관한 연산 수행
# arr % 2 == 0
# [5 8 9 5 0 0 1 7 6 9] % 2 이러면 값 형식 계산이 힘듬
# [5 8 9 5 0 0 1 7 6 9] % [5 8 9 5 0 0 1 7 6 9] 여기서
# [5 8 9 5 0 0 1 7 6 9] % [2 2 2 2 2 2 2 2 2 2] 변경이 되고 브로드캐스팅 된다.
# [1 0 1 1 0 0 1 1 0 1] 으로 값이 나온다.
# [false true false false true true fasle false true false] 으로 변경

print(arr%2 == 0) # boolean mask
print(arr[arr%2 == 0]) # mask 자체를 넣어버림 저 false true 넣어버림 계산
                    # [8 0 0 6] mask 자체 계산식을 넣어서


np.random.seed(1)
arr = np.random.randint(0,10,(3,4)) #2차원으로 만듬
print(arr)

print(arr % 2 == 0) # boolean mask
print(arr[arr % 2 == 0])

# boolean indexing은 조건을 통해서 원하는 데어터를 추출하기 위해 사용

[5 8 9 5 0 0 1 7 6 9]
[False  True False False  True  True False False  True False]
[8 0 0 6]
[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]
[[False  True False False]
 [ True  True False False]
 [ True False  True  True]]
[8 0 0 6 2 4]


In [ ]:
# fancy indexing
# 배열에 index배열 전달 요소 참조하는 방식
np.random.seed(1)
arr = np.random.randint(0,10,(3,4)) #2차원으로 만듬
print(arr)


# print(arr[2,0])
# print(arr[2,[0,2]]) #배열 6추출  [0,2] 2라는 숫자 가지고 와라

#배열에 indexing 배열 전달하여 배열 요소를 참조하라
# 다른 방법

# 8 ,5 ,9 ,4 를 추출한다.
print(arr[[0,2],[1,3]]) # 틀리다.[8,4]만 추출
                        # 여러차원 fancy indexing 있음
                        # 우리가 원하는 값이 안나옴
                        # 함수 제공
np.ix_([0,2],[1,3])     # 문제를 해결하기위해 쓰는 함수 numpy함수
print(arr[np.ix_([0,2],[1,3])]) # 여러개 slicing 안될때 fancy 할때 근데 위에처럼 값이
                               #값이 안나와서 수식이 필요하다.


[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]
[8 4]
[[8 5]
 [9 4]]


In [ ]:
# 간단한 문제
arr1 = np.array([[1,2,3],[4,5,6]]) # 2행 3열 짜리 2차원
arr2 = np.array([[10,11,12],[13,14,15]]) # 2행 3열 짜리 2차원

print(arr1)
print(arr2)

# 4칙 연산을 수행
print(arr1+arr2)
# 사칙 연산을 할 경우 같은 위치에 직접 연산수행
# python은 list는 + 연산하면 연결
# arr1 arr2.reshape(3,2) # arr2 (2,3에서 3행 2열로 변경)

print(np.matmul(arr1,arr2.reshape(3,2))) #결과 2*3 3*2 은 ? 2*2


[[1 2 3]
 [4 5 6]]
[[10 11 12]
 [13 14 15]]
[[11 13 15]
 [17 19 21]]
[[ 76  82]
 [184 199]]


In [ ]:
# numpy는 수치 연산에 특화된 라이브러리
# 집계 함수를 제공
# 합, 평균,

arr = np.arange(1,7,1).reshape(2,3).copy() # 1차원 1씩 증가 시키고 2차원 만들고 다시 2차원 numpy 만들기
print(arr)

print(np.sum(arr)) # 21 값 전부안의 값 합치기 이 배열의 합
print(arr.sum())   # 21 배열 값 더하기
print(arr.mean()) #21 일반 세상에서는 평균 => average, 수학적 계산 평균= mean
print(arr.max()) # 6 가장 큰 값
print(arr.min()) # 1 가장 작은 값

print(arr.argmax()) # max 찾아서 #(1,2) 1차원으로 변경해서 가장 큰값을 index 값
print(arr.std()) # 표준편차



[[1 2 3]
 [4 5 6]]
21
21
3.5
6
1
5
1.707825127659933


In [ ]:
# numpy 모든 집계 함수 axis 기준으로 계산
# 예제들은 axis 고려한게 없다. axis = none 으로 계산
# 전체를 대상으로 함수를 적용

arr = np.arange(1,7,1)
print(arr)

arr.sum(axis=0) # 축을 넣어줘야함 axis 숫자로 표현
                # axis 1차원 일때 3차원 면 행 렬

arr1 = np.arange(1,7,1).reshape(3,2)
print(arr1)
print(arr1.sum())       # 21
print(arr1.sum(axis=0)) # [9,12] 행 방향이여서 [1+3+5 2+4+6]
print(arr1.sum(axis=1)) # [3,7,11] 열방향 [1+2, 3+4, 5+6]

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
21
[ 9 12]
[ 3  7 11]


In [ ]:
# 연습문제

# 2차원 ndarray
# 1부터 16 까지 숫자로 구성 4x4  2차원 ndarray 생성
# <조건> boolen indexing
# 이렇게 만들어진 ndarray 안에 10 보자 큰 숫자 몇개 ?

# 코드상으로

#arr = np.arange(16).reshape(4,4)
arr = np.arange(1,17,1).reshape(4,4)
print(arr)
print(arr>10)
print(arr[arr>10])
print(len(arr))

print((arr>10).sum())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[False False False False]
 [False False False False]
 [False False False  True]
 [ True  True  True  True]]
[11 12 13 14 15]
4


In [ ]:
# numpy 내용 정리 하기
# pandas 실제 데이터 분석 데이터 탐색을 라이브 생각
